name: Tests

on: [ push, pull_request ]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Benchmark
        run: go test -bench=. -benchmem ./...

  uinttest:
    strategy:
      matrix:
        go: [ "1.18", "1.19", "1.20", "1.21", "1.22", "1.23" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache: true # set false for self-hosted
      - name: Unit Test
        run: go test -race ./...
